# Generated by Django 5.2.12 on 2026-05-25 10:36

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Laki-laki'), ('fem', 'Perempuan')], max_length=10)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password_2', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'guru',
            },
            bases=(api.models.AuthAccountMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Halaqoh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Laki-laki'), ('fem', 'Perempuan')], max_length=10)),
                ('guru', models.OneToOneField(db_column='guru_id', on_delete=django.db.models.deletion.CASCADE, related_name='halaqoh', to='api.guru')),
            ],
            options={
                'db_table': 'halaqoh',
            },
        ),
        migrations.CreateModel(
            name='Murid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Laki-laki'), ('fem', 'Perempuan')], max_length=10)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password_2', models.CharField(max_length=255)),
                ('halaqoh', models.ForeignKey(blank=True, db_column='halaqoh_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='murid_list', to='api.halaqoh')),
            ],
            options={
                'db_table': 'murid',
            },
            bases=(api.models.AuthAccountMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Mutabaah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('nama_surah', models.CharField(max_length=100)),
                ('ayat', models.CharField(max_length=50)),
                ('note', models.CharField(choices=[('ziyadah', 'Ziyadah'), ('murajaah', "Muraja'ah")], max_length=20)),
                ('keterangan', models.CharField(blank=True, max_length=255, null=True)),
                ('murid', models.ForeignKey(db_column='murid_id', on_delete=django.db.models.deletion.CASCADE, related_name='mutabaah_list', to='api.murid')),
            ],
            options={
                'db_table': 'mutabaah',
                'ordering': ['-tanggal'],
            },
        ),
    ]
