# Generated by Django 6.0.5 on 2026-05-30 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'chat_room',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('guru', 'Guru'), ('murid', 'Murid')], max_length=10)),
                ('sender_id', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(db_column='room_id', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.chatroom')),
            ],
            options={
                'db_table': 'chat_message',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Guru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Laki-laki'), ('fem', 'Perempuan')], max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guru_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'guru',
            },
        ),
        migrations.CreateModel(
            name='Halaqoh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Laki-laki'), ('fem', 'Perempuan')], max_length=10)),
                ('jadwal', models.CharField(blank=True, default='', max_length=200)),
                ('guru', models.ForeignKey(db_column='guru_id', on_delete=django.db.models.deletion.CASCADE, related_name='halaqoh_list', to='api.guru')),
            ],
            options={
                'db_table': 'halaqoh',
            },
        ),
        migrations.AddField(
            model_name='chatroom',
            name='halaqoh',
            field=models.ForeignKey(db_column='halaqoh_id', on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='api.halaqoh'),
        ),
        migrations.CreateModel(
            name='Murid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Laki-laki'), ('fem', 'Perempuan')], max_length=10)),
                ('status_join', models.CharField(default='pending', max_length=20)),
                ('halaqoh', models.ForeignKey(blank=True, db_column='halaqoh_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='murid_list', to='api.halaqoh')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='murid_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'murid',
            },
        ),
        migrations.AddField(
            model_name='chatroom',
            name='murid',
            field=models.OneToOneField(db_column='murid_id', on_delete=django.db.models.deletion.CASCADE, related_name='chat_room', to='api.murid'),
        ),
        migrations.CreateModel(
            name='Mutabaah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('nama_surah', models.CharField(max_length=100)),
                ('ayat', models.CharField(max_length=50)),
                ('note', models.CharField(choices=[('ziyadah', 'Ziyadah'), ('murajaah', "Muraja'ah")], max_length=20)),
                ('keterangan', models.CharField(blank=True, max_length=255, null=True)),
                ('murid', models.ForeignKey(db_column='murid_id', on_delete=django.db.models.deletion.CASCADE, related_name='mutabaah_list', to='api.murid')),
            ],
            options={
                'db_table': 'mutabaah',
                'ordering': ['-tanggal'],
            },
        ),
    ]
