# Generated by Django 5.2.12 on 2026-05-29 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='halaqoh',
            name='jadwal',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('halaqoh', models.ForeignKey(db_column='halaqoh_id', on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='api.halaqoh')),
                ('murid', models.OneToOneField(db_column='murid_id', on_delete=django.db.models.deletion.CASCADE, related_name='chat_room', to='api.murid')),
            ],
            options={
                'db_table': 'chat_room',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('guru', 'Guru'), ('murid', 'Murid')], max_length=10)),
                ('sender_id', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(db_column='room_id', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.chatroom')),
            ],
            options={
                'db_table': 'chat_message',
                'ordering': ['created_at'],
            },
        ),
    ]
