# Generated by Django 5.0.3 on 2026-05-29 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_halaqoh_jadwal_chatroom_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='murid',
            name='status_join',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='halaqoh',
            name='guru',
            field=models.ForeignKey(db_column='guru_id', on_delete=django.db.models.deletion.CASCADE, related_name='halaqoh_list', to='api.guru'),
        ),
        migrations.AlterModelTable(
            name='halaqoh',
            table=None,
        ),
    ]
